M48
; DRILL file {KiCad 8.0.1-rc1} date 2024-04-19T00:03:45-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-19T00:03:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1300
%
G90
G05
T1
X5.078Y-3.5588
X5.078Y-4.7088
X6.6142Y-3.5588
X6.6142Y-4.7088
M30
